name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      IMAGE_NAME: daanifm/recomendador:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Run container (test)
        run: |
          docker run -e API_KEY=$API_KEY -d -p 7860:7860 $IMAGE_NAME
          sleep 10
          docker ps -a
